version: '3'

services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-2333}:2333"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped 